// Generated by CoffeeScript 1.3.3
(function() {
  var BaseTool,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BaseTool = (function() {

    BaseTool.prototype.required_opts = ['data', 'selector', 'el', 'keys'];

    function BaseTool(opts) {
      this.uglifyKey = __bind(this.uglifyKey, this);

      this.prettyKey = __bind(this.prettyKey, this);

      this.selectKey = __bind(this.selectKey, this);

      this.selectElement = __bind(this.selectElement, this);

      var opt, _i, _len, _ref;
      _ref = this.required_opts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        opt = _ref[_i];
        if (!_.has(opts, opt)) {
          throw "missing option " + opt;
        }
      }
      this.data = opts.data;
      this.selector = opts.selector;
      this.keys = opts.key;
      this.el = opts.el;
      this.selectElementCb = opts.selectElementCb || function() {};
      this.selectKeyCb = opts.selectKeyCb || function() {};
      this.selectedElement = opts.selectedElement || null;
      this.selectedKey = opts.selectedKey || 'id';
    }

    BaseTool.prototype.selectElement = function(id) {
      this.selectedElement = id;
      this.selectElementCb(id);
      return this.start();
    };

    BaseTool.prototype.selectKey = function(key) {
      this.selectedKey = key;
      this.selectKeyCb(key);
      return this.start();
    };

    BaseTool.prototype.prettyKey = function(key) {
      return this.capitalizeWords(this.underscoresToSpaces(key));
    };

    BaseTool.prototype.uglifyKey = function(key) {
      return this.spacesToUnderscores(this.lowercaseWords(key));
    };

    BaseTool.prototype.underscoresToSpaces = function(string) {
      return string.replace(/_/g, " ");
    };

    BaseTool.prototype.capitalizeWords = function(string) {
      return string.replace(/(\b[a-z])/g, function(char) {
        return char.toUpperCase();
      });
    };

    BaseTool.prototype.spacesToUnderscores = function(string) {
      return string.replace(/\s/g, "_");
    };

    BaseTool.prototype.lowercaseWords = function(string) {
      return string.replace(/(\b[A-Z])/g, function(char) {
        return char.toLowerCase();
      });
    };

    return BaseTool;

  })();

  if (typeof require === 'function' && typeof module === 'object' && typeof exports === 'object') {
    module.exports = BaseTool;
  } else {
    window.Ubret['BaseTool'] = BaseTool;
  }

}).call(this);
