// Generated by CoffeeScript 1.3.3
(function() {
  var BaseTool,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BaseTool = (function() {

    BaseTool.prototype.required_opts = ['data', 'selector', 'el', 'keys'];

    function BaseTool(opts) {
      this.createDimensions = __bind(this.createDimensions, this);

      this.selectKey = __bind(this.selectKey, this);

      this.selectElements = __bind(this.selectElements, this);

      this.uglifyKey = __bind(this.uglifyKey, this);

      this.prettyKey = __bind(this.prettyKey, this);

      this.getTemplate = __bind(this.getTemplate, this);

      var opt, _i, _len, _ref;
      console.log('BaseTool');
      _ref = this.required_opts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        opt = _ref[_i];
        if (!_.has(opts, opt)) {
          throw "missing option " + opt;
        }
      }
      this.data = crossfilter(opts.data);
      this.selector = opts.selector;
      this.keys = opts.keys;
      this.el = opts.el;
      this.selectElementCb = opts.selectElementCb || function() {};
      this.selectKeyCb = opts.selectKeyCb || function() {};
      this.selectedElement = opts.selectedElement || null;
      this.selectedKey = opts.selectedKey || 'id';
      console.log(this.keys);
      this.createDimensions();
    }

    BaseTool.prototype.getTemplate = function() {
      return this.template;
    };

    BaseTool.prototype.prettyKey = function(key) {
      return this.capitalizeWords(this.underscoresToSpaces(key));
    };

    BaseTool.prototype.uglifyKey = function(key) {
      return this.spacesToUnderscores(this.lowercaseWords(key));
    };

    BaseTool.prototype.selectElements = function(ids) {
      this.selectedElements = ids;
      this.selectElementsCb(ids);
      return this.start();
    };

    BaseTool.prototype.selectKey = function(key) {
      this.selectedKey = key;
      this.selectKeyCb(key);
      return this.start();
    };

    BaseTool.prototype.createDimensions = function() {
      var key, _i, _len, _ref, _results;
      this.dimensions = new Object;
      _ref = this.keys;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        this.dimensions.id = this.data.dimension(function(d) {
          return d.id;
        });
        _results.push(this.dimensions[key] = this.data.dimension(function(d) {
          return d[key];
        }));
      }
      return _results;
    };

    BaseTool.prototype.addFilters = function() {};

    BaseTool.prototype.formatKey = function(key) {
      return (key.replace(/_/g, " ")).replace(/(\b[a-z])/g, function(char) {
        return char.toUpperCase();
      });
    };

    return BaseTool;

  })();

  if (typeof require === 'function' && typeof module === 'object' && typeof exports === 'object') {
    module.exports = BaseTool;
  } else {
    window.Ubret['BaseTool'] = BaseTool;
  }

}).call(this);
