// Generated by CoffeeScript 1.3.3
(function() {
  var BaseTool, Graph,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseTool = window.Ubret.BaseTool || require('./base_tool');

  Graph = (function(_super) {

    __extends(Graph, _super);

    function Graph(opts) {
      this.createYAxis = __bind(this.createYAxis, this);

      this.createXAxis = __bind(this.createXAxis, this);

      this.createGraph = __bind(this.createGraph, this);

      var compiled;
      console.log('Graph');
      Graph.__super__.constructor.call(this, opts);
      compiled = _.template(this.template, {
        selector: this.selector
      });
      this.el.html(compiled);
      this.height = opts.width || this.el.height();
      this.width = opts.height || this.el.width();
      this.margin = opts.margin || {
        left: 60,
        top: 20,
        bottom: 60,
        right: 40
      };
      this.format = opts.format ? d3.format(opts.format) : d3.format(',.02f');
      this.color = opts.color || '#0172E6';
      this.selectionColor = opts.selectionColor || '#CD3E20';
    }

    Graph.prototype.createGraph = function() {
      var graphHeight, graphWidth;
      graphHeight = this.height - (this.margin.top + this.margin.bottom);
      graphWidth = this.width - (this.margin.left + this.margin.right);
      return this.svg = d3.select(this.selector).append('svg').attr('height', graphHeight).attr('width', graphWidth);
    };

    Graph.prototype.createXAxis = function(dataSet, ticks) {
      var xAxis, xDomain;
      xDomain = d3.extent(dataSet, d(function() {
        return d.x;
      }));
      if (xDomain.length === 0) {
        xDomain = [0, 1];
      }
      this.x = d3.scale.linear().domain(xDomain).range([0, this.graphWidth]);
      return xAxis = d3.svg.axis().scale(this.x).orient('bottom');
    };

    Graph.prototype.createYAxis = function(dataSet, ticks) {
      var yDomain;
      yDomain = d3.extent(dataSet, d(function() {
        return d.y;
      }));
      if (yDomain.length === 0) {
        yDomain = [0, 1];
      }
      return this.y = d3.scale.linear().domain(yDomain).range(0);
    };

    return Graph;

  })(BaseTool);

  if (typeof require === 'function' && typeof module === 'object' && typeof exports === 'object') {
    module.exports = Graph;
  } else {
    window.Ubret['Graph'] = Graph;
  }

}).call(this);
