// Generated by CoffeeScript 1.3.3
(function() {
  var Graph, Scatter2D,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Graph = window.Ubret.Graph || require('./Graph');

  Scatter2D = (function(_super) {

    __extends(Scatter2D, _super);

    Scatter2D.prototype.axes = 2;

    Scatter2D.prototype.template = "<div class=\"histogram\">\n  <div id=\"<%- selector %>\">\n    <svg></svg>\n  </div>\n</div>";

    function Scatter2D(opts) {
      this.draw = __bind(this.draw, this);
      console.log('Scatter2D');
      Scatter2D.__super__.constructor.call(this, opts);
    }

    Scatter2D.prototype.draw = function() {
      var data, xDomain, yDomain,
        _this = this;
      console.log('Scatter2D draw');
      data = this.dimensions[this.axis1].top(Infinity);
      data = _.map(data, function(d) {
        return _.pick(d, d[_this.axis1], d[_this.axis2]);
      });
      xDomain = d3.extent(data, function(d) {
        return d[_this.axis1];
      });
      yDomain = d3.extent(data, function(d) {
        return d[_this.axis2];
      });
      return console.log(xDomain, yDomain);
    };

    return Scatter2D;

  })(Graph);

  if (typeof require === 'function' && typeof module === 'object' && typeof exports === 'object') {
    module.exports = Scatter2D;
  } else {
    window.Ubret['Scatter2D'] = Scatter2D;
  }

}).call(this);
