// Generated by CoffeeScript 1.4.0
(function() {
  var BaseTool, SubjectViewer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseTool = window.Ubret.BaseTool || require('./base_tool');

  SubjectViewer = (function(_super) {

    __extends(SubjectViewer, _super);

    function SubjectViewer() {
      this.start = __bind(this.start, this);
      return SubjectViewer.__super__.constructor.apply(this, arguments);
    }

    SubjectViewer.prototype.template = "<ul>\n  <% for(i = 0; i < keys.length; i++) { %>\n    <li>\n      <%- keys[i] %>: <%- subject[keys[i]] %>\n    </li>\n  <% } %>\n</ul>";

    SubjectViewer.prototype.start = function() {
      var compiled, data, subject,
        _this = this;
      data = this.dimensions.id.top(Infinity);
      if (!this.selectedElements) {
        subject = data[0];
      } else {
        subject = _.find(data, function(record) {
          return record.id === _this.selectedElements[0];
        });
      }
      compiled = _.template(this.template, {
        subject: subject,
        keys: this.keys
      });
      return this.el.html(compiled);
    };

    return SubjectViewer;

  })(BaseTool);

  if (typeof require === 'function' && typeof module === 'object' && typeof exports === 'object') {
    module.exports = SubjectViewer;
  } else {
    window.Ubret['SubjectViewer'] = SubjectViewer;
  }

}).call(this);
