// Generated by CoffeeScript 1.3.3
(function() {
  var Ubret;

  if (typeof require === 'function' && typeof exports === 'object' && typeof module === object) {
    Ubret = {
      Table: require('./controllers/Table')
    };
    module.exports = Ubret;
  } else {
    window.Ubret = new Object;
  }

}).call(this);
