// Generated by CoffeeScript 1.4.0
(function() {
  var Ubret;

  if (typeof require === 'function' && typeof exports === 'object' && typeof module === 'object') {
    Ubret = {
      Map: require('./ubret/map'),
      Statistics: require('./ubret/statistics'),
      SubjectViewer: require('./ubret/subject_viewer'),
      Table: require('./ubret/table')
    };
    module.exports = Ubret;
  } else {
    window.Ubret = {};
  }

}).call(this);
